query searchMasterdata {
  searchMasterdata {
    id
    type
    content
    name
    operator
    simpleStatements {
      error
      object {
        name
        value
        id
      }
      subject
      verb
    }
  }
}
